### ISSUE TITLE
Deploy failing silently on certbot.sh

### ISSUE THREAD

**Issue by 0o-de-lally** [ixc/letsencrypt-docker#1]
@mrmachine 
Seems like something has changed in the dependencies
`docker run -d -t -i -e DOMAINS='www.domain.com' -e EMAIL='email@domain.com' -p 80:80 interaction/letsencrypt:master
`

Exits with code 1, with error:
'WARNING: Tini has been relocated to /sbin/tini.'

**Comment by 0o-de-lally** [comment]
@mrmachine 
Digging deeper, the error is unrelated to tini. Seems to be in  certbot.sh which is failing silently.

**Comment by mrmachine** [comment]
@lpgeiger Thanks for the report. This issue should be fixed in 7917514e2b8f5dd2c4844e4e923ab56d34305e1e and cbd8041a9ef69740476a40ad39384842b81e9c34 and b09bdff64f59bc8bcb7cfef26046943b17db42f4.
